version: '3.3'

services:
  application:
    build: .
    restart: always
    container_name: madrage-back-end-challenge
    ports:
      - 8081:80
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_DB: madrage-back-end-challenge
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./Database:/docker-entrypoint-initdb.d