//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadrageBackEndChallenge.Web.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MadrageBackEndChallenge.Web.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmailAlreadyExistsException {
            get {
                return ResourceManager.GetString("EmailAlreadyExistsException", resourceCulture);
            }
        }
        
        internal static string MaximumLengthValidator {
            get {
                return ResourceManager.GetString("MaximumLengthValidator", resourceCulture);
            }
        }
        
        internal static string MinimumLengthValidator {
            get {
                return ResourceManager.GetString("MinimumLengthValidator", resourceCulture);
            }
        }
        
        internal static string AsyncPredicateValidator {
            get {
                return ResourceManager.GetString("AsyncPredicateValidator", resourceCulture);
            }
        }
        
        internal static string CreditCardValidator {
            get {
                return ResourceManager.GetString("CreditCardValidator", resourceCulture);
            }
        }
        
        internal static string EmailValidator {
            get {
                return ResourceManager.GetString("EmailValidator", resourceCulture);
            }
        }
        
        internal static string EmptyValidator {
            get {
                return ResourceManager.GetString("EmptyValidator", resourceCulture);
            }
        }
        
        internal static string EnumValidator {
            get {
                return ResourceManager.GetString("EnumValidator", resourceCulture);
            }
        }
        
        internal static string EqualValidator {
            get {
                return ResourceManager.GetString("EqualValidator", resourceCulture);
            }
        }
        
        internal static string ExactLengthValidator {
            get {
                return ResourceManager.GetString("ExactLengthValidator", resourceCulture);
            }
        }
        
        internal static string ExclusiveBetweenValidator {
            get {
                return ResourceManager.GetString("ExclusiveBetweenValidator", resourceCulture);
            }
        }
        
        internal static string GreaterThanOrEqualValidator {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualValidator", resourceCulture);
            }
        }
        
        internal static string GreaterThanValidator {
            get {
                return ResourceManager.GetString("GreaterThanValidator", resourceCulture);
            }
        }
        
        internal static string InclusiveBetweenValidator {
            get {
                return ResourceManager.GetString("InclusiveBetweenValidator", resourceCulture);
            }
        }
        
        internal static string LengthValidator {
            get {
                return ResourceManager.GetString("LengthValidator", resourceCulture);
            }
        }
        
        internal static string LessThanOrEqualValidator {
            get {
                return ResourceManager.GetString("LessThanOrEqualValidator", resourceCulture);
            }
        }
        
        internal static string LessThanValidator {
            get {
                return ResourceManager.GetString("LessThanValidator", resourceCulture);
            }
        }
        
        internal static string NotEmptyValidator {
            get {
                return ResourceManager.GetString("NotEmptyValidator", resourceCulture);
            }
        }
        
        internal static string NotEqualValidator {
            get {
                return ResourceManager.GetString("NotEqualValidator", resourceCulture);
            }
        }
        
        internal static string NotNullValidator {
            get {
                return ResourceManager.GetString("NotNullValidator", resourceCulture);
            }
        }
        
        internal static string NullValidator {
            get {
                return ResourceManager.GetString("NullValidator", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PredicateValidator {
            get {
                return ResourceManager.GetString("PredicateValidator", resourceCulture);
            }
        }
        
        internal static string RegularExpressionValidator {
            get {
                return ResourceManager.GetString("RegularExpressionValidator", resourceCulture);
            }
        }
        
        internal static string ScalePrecisionValidator {
            get {
                return ResourceManager.GetString("ScalePrecisionValidator", resourceCulture);
            }
        }
        
        internal static string ValidationException {
            get {
                return ResourceManager.GetString("ValidationException", resourceCulture);
            }
        }
        
        internal static string AuthenticationException {
            get {
                return ResourceManager.GetString("AuthenticationException", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string SystemUnavailable {
            get {
                return ResourceManager.GetString("SystemUnavailable", resourceCulture);
            }
        }
    }
}
